tfmodel = 'subclass'
image = './TF2DeepFloorplan/resources/30939153.jpg'
postprocess = 1
colorize = 1
save = ''
weight = './log/store/G'
loadmethod = 'log'
feature_channels = [256, 128, 64, 32]
backbone = 'vgg16'
feature_names = ["block1_pool", "block2_pool", "block3_pool", "block4_pool", "block5_pool",]